apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth.recommendationservice9
spec:
  selector:
    matchLabels:
      app: recommendationservice
  action: ALLOW 
  rules:
  - to:
    - operation:
        methods: ["POST"]
        paths: ["/hipstershop.RecommendationService/*"]
