apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth.productcatalogservice3
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  action: ALLOW 
  rules:
  - to:
    - operation:
        methods: ["POST"]
        paths: ["/hipstershop.ProductCatalogService/*"]
