apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth.169.254.169.25415
spec:
  selector:
    matchLabels:
      app: 169.254.169.254
  action: ALLOW 
  rules:
  - to:
    - operation:
        methods: ["GET"]
        paths: ["/*"]
