apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth.adservice1
spec:
  selector:
    matchLabels:
      app: adservice
  action: ALLOW 
  rules:
  - to:
    - operation:
        methods: ["POST"]
        paths: ["/hipstershop.AdService/*"]
